### ISSUE TITLE
'App' doesn't copy over necessary dlls on windows

### ISSUE THREAD

**Issue by Jasper-Bekkers** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#100]
I've added this to App.lua locally to work around the issue, but it would need a 32-bit build of OIIO submitted for it to work.

        configuration {}
            postbuildcommands  { 
              'copy "..\\3rdParty\\glew\\bin\\$(Platform)\\glew32.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\glew32.dll"', 
              'copy "..\\3rdParty\\freeglut\\bin\\$(Platform)\\freeglut.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\freeglut.dll"', 
              'copy "..\\3rdParty\\embree\\bin\\$(Platform)\\embree.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\embree.dll"',
              'copy "..\\3rdParty\\embree\\bin\\$(Platform)\\tbb.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\tbb.dll"',
              'copy "..\\3rdParty\\oiio\\bin\\$(Platform)\\OpenImageIO.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\OpenImageIO.dll"',
              'copy "..\\3rdParty\\oiio\\bin\\$(Platform)\\OpenImageIOD.dll" "..\\Bin\\$(ConfigurationName)\\$(Platform)\\OpenImageIOD.dll"' 
            }

**Comment by yozhijk** [comment]
@beasterio , can you build 32-bit OIIO and fix this?

**Comment by yozhijk** [comment]
@Jasper-Bekkers , libs have been added in this commit: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/cb562f01ddaa61240bcac99183fd837d99117d93

**Comment by Jasper-Bekkers** [comment]
In that case can we make sure the code above makes it into App.lua?

**Comment by yozhijk** [comment]
@beasterio could you take care of that?
