### ISSUE TITLE
Material support

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#104]
I'm trying to render high quality ray-traced image using Radeon Rays SDK.

First of all, I need to render various material.
Radeon Rays SDK's library has no material stuff. But I found some materials at the App.proj.
These materials are implemented hard coded and difficult to control it.
Do you have any plan to various material functions?

**Comment by yozhijk** [comment]
@generalistr6 , yes, we have a plan to support some xml-based material spec, however this is lower priority compared to the intersection lib itself. (the renderer only serves as a demo for intersection lib at the moment)

**Comment by generalistr6** [comment]
Recently, my coworker who has CG skills tried the ProRenderer(a.k.a Radeon Renderer) plugin on 3D Max.
There are many material options and templates.
Can I assume that the materials which are created on ProRenderer could be implemented on Radeon Rays?
Because, I heard that Radeon Rays will be the core-background of Radeon Renderer in the future.

**Comment by yozhijk** [comment]
@generalistr6 , RadeonRays is being used in RPR as an intersection framework, however implementation of RPR materials is a separate code base. Although RadeonRays renderer supports pretty much the same set of basic BxDFs, it lacks the flexibility of RPR material system (where you have an option to create procedural entities, perform arithmetic operations on the nodes and so on). As of now we do not have plans to support full complexity of RPR material system in this open-source renderer, but limit ourselves with a basic subset. Forks are free to extend based on that.

**Comment by generalistr6** [comment]
Thanks for information about RPR.
Can I know when the open source of RPR is released?

**Comment by yozhijk** [comment]
@generalistr6 we do not have exact date atm, stay tuned

**Comment by generalistr6** [comment]
@yozhijk I'll close this issue because implementing xml-based material is low priority and the issue title is too general.
