### ISSUE TITLE
Transparent Material

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#105]
I'm going to express simple transparent material using 'kIdealRefract'.
Tinyobj material's dissolve means alpha value.
Can I control alpha value using dissolve parameter?

**Comment by yozhijk** [comment]
Hi @generalistr6 ,

I do not think this parameter has been hooked up in the demo, however nothing prevents you from doing that. Using kIdealRefract with IOR == 1 for transparency is going to produce correct result, although slightly inefficient (it does unnecesssary refraction calculations to calculate trivial pass-thru ray direction). You can use kPassthrough BRDF to make it more efficient. General guideline would be to create kMix shader blending, say, kLambert and kPassthrough. Your blend weight for kMix shader is controlling the amount of transparency in this case (weight parameter can be textured).

**Comment by yozhijk** [comment]
I have just merged weight texturing functionality I implemented the other day (https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/0a34f569410c6023531568273aa6297a997ef044)

Some examples of textured blends follow.
<img width="800" alt="4" src="https://cloud.githubusercontent.com/assets/4111901/20343297/105547d0-abee-11e6-8805-bf8f73ac46c0.png">
<img width="400" alt="1" src="https://cloud.githubusercontent.com/assets/4111901/20343296/10543c14-abee-11e6-98bd-9cb509d40b28.png">

<img width="800" alt="3" src="https://cloud.githubusercontent.com/assets/4111901/20343298/10574f94-abee-11e6-9e77-cfe6b3ac1e9f.png">

<img width="960" alt="2" src="https://cloud.githubusercontent.com/assets/4111901/20343315/22e71702-abee-11e6-973e-599877afbb1c.png">

**Comment by generalistr6** [comment]
Thank you for your prompt reply. I just started watching how the 'Kmix' works.
First of all, your last commit, it seems, has no resources such as 'rust.jpg', 'rust_bw.jpg' and 'metal_rough0001.png'.

I have another questions about 'Transparent Material'.
By the code of 'texture.cl', there is no access to the alpha value of a texture.
How can I express the alpha value of a texture?

**Comment by yozhijk** [comment]
@generalistr6 , right, currently they are float3, this is trivial change, will implement today.

**Comment by yozhijk** [comment]
Missing textures are fixed in this commit: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/3f105be35e7cca69e2ac07d7b9bef3b5d4274852

**Comment by yozhijk** [comment]
I have exposed alpha-channel here using Texture_GetValue4f function: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/3ce5029889fba63b683d3a450aadfbd9a5a79c1a

**Comment by generalistr6** [comment]
Thanks.
I confirmed the Texture_GetValue4f function, but there is no use of this function.
I want to render transparent texture as diffuse color.
My solution is using KMix as you recommended before.
```
float weight = 0.f;
				if (mat.nsmapidx == -1)
				{
					weight = 1.f - mat.ns;
				}
				else
				{
					weight = 1.f - Texture_GetValue4f(make_float4(0.f, 0.f, 0.f, 1.f), dg->uv, TEXTURE_ARGS_IDX(mat.nsmapidx)).w;
				}

                if (sample < weight)
                {
                    // Sample top
```

**Comment by yozhijk** [comment]
@generalistr6 , should not affect perf too much, since we are doing stochastic splitting and evaluating only one of the blend arguments every pass. using transparency as one of the blend arguments is even cheaper than regular blend since it is very simple brdf.

**Comment by yozhijk** [comment]
Closing this one: nothing to fix here
