### ISSUE TITLE
Texture coordinate bug

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#106]
The last committed source of master, it seems, represent wrong texture coordinate compare with my last downloaded version.
My last version up to dated on Oct 31 2016, it work good for texture coordinate.

**Comment by yozhijk** [comment]
@generalistr6 , could you provide a repro case?

**Comment by generalistr6** [comment]
I found the different line.

[scene.cpp]
float2 uv = **0.2f *** float2(objshapes[s].mesh.texcoords[2 * i], objshapes[s].mesh.texcoords[2 * i + 1]);

when I changed as below, it works fine.
float2 uv = float2(objshapes[s].mesh.texcoords[2 * i], objshapes[s].mesh.texcoords[2 * i + 1]);

**Comment by yozhijk** [comment]
Should be fixed here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/cb562f01ddaa61240bcac99183fd837d99117d93

Can you check?

**Comment by generalistr6** [comment]
Thanks. It works correctly.
