### ISSUE TITLE
How to multiply blending diffuse color and texture.

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#110]
I want to multiply diffuse color and diffuse texture as below.
`DestinationColor.rgb = diffuseColor.rgb * diffuseTexture.rgb;`
I tried using KMix and kFresnelBlend but it seams that these cannot express multiply blending.
Is there any way to do this?

**Comment by generalistr6** [comment]
```
float3 Texture_GetValue3f(
                // Value
                float3 v,
                // Texture coordinate
                float2 uv,
                // Texture args
                TEXTURE_ARG_LIST_IDX(texidx)
                )
{
    // If texture present sample from texture
    if (texidx != -1)
    {
        // Sample texture
	float3 ret = native_powr(Texture_Sample2D(uv, TEXTURE_ARGS_IDX(texidx)), 2.2f);
	return ret = ret * v;
    }
    
    // Return fixed color otherwise
    return v;
}
```
I changed the Texture_GetValue3f function at texture.cl.
It seams good. If you don't have any comment, I'll close this issue.

**Comment by yozhijk** [comment]
Ok, closing this one then.
