### ISSUE TITLE
Bump Texture Implement

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#112]
There is normal texture is used in App project, but it is expressed as specular texture of a material.
Do you have plan to support bump texture which can replace geometric normal?

**Comment by yozhijk** [comment]
Hi @generalistr6 ,

It is supported, just put it to nmapidx slot of a material. Example attached 
![unnamed](https://cloud.githubusercontent.com/assets/4111901/20621986/1399befc-b301-11e6-8ef7-be3108c59931.jpg)
![unnamed 1](https://cloud.githubusercontent.com/assets/4111901/20621987/139c203e-b301-11e6-90ab-d307a8e7f5c0.jpg)

(floor and orb are both bump mapped).

**Comment by yozhijk** [comment]
Or you meant normal map (3 component normal textures) vs bump map (height map) support?

**Comment by generalistr6** [comment]
I meant normal map.
It was my lack of understanding how to apply normal map.
I resolved to apply normal map by using nmapidx of kLambert material.

I have a question about ApplyNormalMap function.
There is a term of multiply 0.5f to geometry normal.
`dg->n = normalize(mappednormal.z *  dg->n * 0.5f + mappednormal.x * dg->dpdu + mappednormal.y * dg->dpdv);`
Can I assume this value as intensity of normal which can be customized?
I think it should be different value, depending on material.

**Comment by yozhijk** [comment]
@generalistr6 you are right, this value is essentually normal map "strength", I just did not have time to expose it as a tunable parameter.

**Comment by generalistr6** [comment]
@yozhijk Do you have a plan to expose normal strength soon?
If so, I would close this issue then. Or I'll do it now.

**Comment by yozhijk** [comment]
@generalistr6 , I do not think I am going to do that in coming days, so please go ahead

**Comment by generalistr6** [comment]
@yozhijk Ok. I'll closing this issue. thanks.
