### ISSUE TITLE
Implement dirty flag for kGeometryTransform

### ISSUE THREAD

**Issue by generalistr6** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#114]
Hi.
There is kGeometryTransform, dirty flag, not yet implemented.
To update this dirty flag, I changed shape's matrix and called RecompileFull and ReloadIntersector.
I works but it seems not good performance.
Do you have plan to apply kGeometryTransform flag?

**Comment by yozhijk** [comment]
@generalistr6 I am reworking scene management in scene-interface branch, this flag will be implemented

**Comment by yozhijk** [comment]
Done in Baikal renderer repo
