### ISSUE TITLE
Crash when rendering OBJ with "Odd-size" texture image on GPU

### ISSUE THREAD

**Issue by Inyong** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#117]
Hi, I found a crash when rendering OBJ file with "odd-size" texture image on GPU.

I attached my simple zipped file. (obj + mtl + jpg) [rect.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/files/665947/rect.zip)
If I change the (attached) image's from odd-size (e.g. 313 x 161) to even-size (314 x 162), it works well. But, with odd-size, it crashes at the beginning of program. (The crash occurs only on GPU (Mode::kUseSingleGpu). CPU is fine)

FYI,  this bug has occurred recently. If i use old versions (before October, 2016), I have never experienced this bug.

Test Environment (GPU) : NVIDIA GrForce GTX 750 Ti

**Comment by yozhijk** [comment]
Hi @Inyong,

I have noticed this too on nvidia hw. Will investigate.

**Comment by Inyong** [comment]
@yozhijk  Thanks millions!

**Comment by yozhijk** [comment]
@beasterio fixed here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/pull/122/commits/31d2b387781e993e7ea85dc08b177271ba308e90

@Inyong, could you verify?

**Comment by Inyong** [comment]
@yozhijk  , Great! I've verified, it works perfectly (on my GPU, NVIDIA GrForce GTX 750 Ti )! Thank you!

**Comment by yozhijk** [comment]
@Inyong , thanks, closing the issue
