### ISSUE TITLE
Problems

### ISSUE THREAD

**Issue by acterhd** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#119]
Hello. I can't found any simple example for Radeon Rays. Also, I have problem with Interop with OpenGL. I seen that you using only direct pointers. Pls, add support for OpenGL or real OpenCL interop. Need load OpenCL buffers directly, without CPU overhead.

**Comment by yozhijk** [comment]
@acterhd could you describe in more details what does real interop mean? Taking geometry data out of GL buffers?

**Comment by yozhijk** [comment]
Tutorials have been added
