### ISSUE TITLE
Building App in Xcode fails

### ISSUE THREAD

**Issue by AberrantWolf** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#123]
Following the directions from the readme (I already have homebrew installed), I installed OpenImageIO and generated the project files.

I can open RadeonRays.xcworspace and build RadeonRays without issue, however switching to the App and building generates linker errors:
ld: warning: directory not found for option '-L../3rdparty/oiio16/lib/x64'
Undefined symbols for architecture x86_64:
  "OpenImageIO::v1_6::ImageInput::open(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, OpenImageIO::v1_6::ImageSpec const*)", referenced from:
      Baikal::LoadTexture(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, Baikal::Scene::Texture&, std::__1::vector<std::__1::unique_ptr<char [], std::__1::default_delete<char []> >, std::__1::allocator<std::__1::unique_ptr<char [], std::__1::default_delete<char []> > > >&) in scene.o
...

And so on.

The problem seems to be that OpenImageIO is now version 1.7 rather than 1.6, and so the namespace in the referenced header files doesn't match the namespace in the installed libraries.

I can change App/App.lua to point to where Homebrew install them, but then I get a bunch of errors indicating that OpenImageIO's headers can't be found using angled brackets from OpenImageIO's `simd.h` header file. Switching them to quoted includes gets past that, though is obviously undesireable.

Note that I needed to add /usr/local/include to the includedirs method because otherwise it wasn't finding the OpenEXR headers, either, and I also had to change them to be in quotes rather than angle brackets.

I can move the relevant include paths from "User Header Search Paths" to just "Header Search Paths" inside the Xcode project's settings, which fixes the issue, but sadly I don't know premake well enough to know how to get it to use the proper include path so that the setting is correct when the project gets re-generated.

**Comment by yozhijk** [comment]
@AberrantWolf thanks for fixing it. Merged: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/62e7d63476718df59ebb67b1e23dffc42213586c
