### ISSUE TITLE
The operator for matrix-float3 multiplication is very confusing and error-prone.

### ISSUE THREAD

**Issue by KaoCC** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#155]
Greetings !

The overloaded operator for matrix multiplication that takes a `matrix` and a `float3` as parameters is very confusing due to the following description:

By design, a `RadeonRays::matrix` is basically a 4\*4 matrix, and yet a `RadeonRays::float3` is a 4\*1 matrix ( Note that `float4` is an alias (typedef) of `float3`). However, the overloaded `operator*` only operates on the 3\*3 sub-matrix from a `RadeonRays::matrix` and multiplies it with a 3\*1 matrix extracted from `float4`. The rest of the elements are dropped quietly. Therefore, if you create a 4\*4 translation matrix and multiply it with a `float4`, you will not get the expected result since the rightmost column does not contribute to the multiplication.

I can provide a quick fix for this issue.

**Comment by KaoCC** [comment]
#156

**Comment by yozhijk** [comment]
@KaoCC thanks for fixing this, merged
