### ISSUE TITLE
--shared_calc cause build error on VS2015

### ISSUE THREAD

**Issue by FlorentGuinier** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#157]
Building radeonrays after generating the Visual Studio 2015 solution with the --shared_calc fla will cause build errors :

- At compile time
Error E0167	argument of type "const char *" is incompatible with parameter of type "LPCWSTR"	RadeonRays	...\RadeonRays_SDK\RadeonRays\src\api\radeon_rays.cpp	103	
![image](https://user-images.githubusercontent.com/20201082/29811483-e7d3ea0e-8ca3-11e7-9231-392d700b1515.png)

- At link time (if compilation is fixed before)
dl.lib cannot be found.

This was discovered while using the following solution prepare step :
.\Tools\premake\win\premake5.exe vs2015 --use_embree --use_opencl --embed_kernels --shared_calc --safe_math

**Comment by yozhijk** [comment]
@beasterio could you fix that?

**Comment by yozhijk** [comment]
@FlorentGuinier Merged: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/27a54a8aa7270f6981acce70ea9db7ae69d5d71d
