### ISSUE TITLE
compilation problem with embree from CS 91fd592b22225169e828fecd38298f49747f53af

### ISSUE THREAD

**Issue by FlorentGuinier** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#160]
Seems that Radeon Rays SDK branch on github fails to compile and has errors regarding `embree_intersection_device.cpp` in lines 119, 174 and 503. This error has been introduced in this commit: `91fd592b22225169e828fecd38298f49747f53af`. Before that revision, VS project compiles without a problem.

**Comment by FlorentGuinier** [comment]
one need to generate the project using --use_embree to get the problem (only tested on windows)
for example : .\Tools\premake\win\premake5.exe vs2015 --use_embree

**Comment by NTimmons** [comment]
This bug looks like it was what came from a change to the flags not being removed in all files across the codebase. I have fixed the specific error by removing the now undefined flag.
