### ISSUE TITLE
IntersectionApi Create triggers exception

### ISSUE THREAD

**Issue by Trylz** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#164]
Hi,

I am trying to use the SDK but i have a runtime error saying "Cannot read the contents of a file" when creating the intersection api.

Everything works fine when using the binaires from the Baikal renderer.

See [link](https://community.amd.com/thread/223260) for more details

**Comment by aykuznetsova** [comment]
I am running into the same problem. I think this is due to relative paths being used, e.g. https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/blob/3de8f3f81f174194039f70d69fdf40afbc86828a/RadeonRays/src/intersector/intersector_skip_links.cpp#L104

**Comment by qhaas** [comment]
If you don't want to deal with path issues to your kernels, embed them by using the `-DRR_EMBED_KERNELS=ON` flag in your CMake call.

**Comment by Trylz** [comment]
Thanks i will try it when i update to the latest library.

**Comment by Trylz** [comment]
Works like a charm. Thanks a lot :)
