### ISSUE TITLE
How to cmake RadeonRays_SDK correctly ? 

### ISSUE THREAD

**Issue by itmanager85** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#198]
'cmake -G "Visual Studio 14 2015 Win64"' in command line outs 'CMake Error: The source directory "E:/Users/admin" does not appear to contain CMakeLists.txt'.

so, I used cmake-gui but parametr "-G" I don't know where to input.

so, it compiles but UnitTest outs this below (don't find how to spoiler this in yours editor), what's wrong ? and how to cmake Tutorials ? (if use Tutorials folder in cmake - in MVC it's contains only "ZERO_CHECK" project)

[==========] Running 67 tests from 6 test cases.
[----------] Global test environment set-up.
[----------] 13 tests from CalcTestkOpenCL
[ RUN      ] CalcTestkOpenCL.Create
[       OK ] CalcTestkOpenCL.Create (286 ms)
[ RUN      ] CalcTestkOpenCL.EnumDevices
[       OK ] CalcTestkOpenCL.EnumDevices (0 ms)
[ RUN      ] CalcTestkOpenCL.CreateDevice
[       OK ] CalcTestkOpenCL.CreateDevice (33 ms)
[ RUN      ] CalcTestkOpenCL.CreateBuffer
[       OK ] CalcTestkOpenCL.CreateBuffer (11 ms)
[ RUN      ] CalcTestkOpenCL.CreateBufferZeroSize
[       OK ] CalcTestkOpenCL.CreateBufferZeroSize (11 ms)
[ RUN      ] CalcTestkOpenCL.CreateBufferInitialData
[       OK ] CalcTestkOpenCL.CreateBufferInitialData (19 ms)
[ RUN      ] CalcTestkOpenCL.ReadWriteBuffer
[       OK ] CalcTestkOpenCL.ReadWriteBuffer (11 ms)
[ RUN      ] CalcTestkOpenCL.ReadWriteTypedBuffer
[       OK ] CalcTestkOpenCL.ReadWriteTypedBuffer (10 ms)
[ RUN      ] CalcTestkOpenCL.MapBuffer
[       OK ] CalcTestkOpenCL.MapBuffer (11 ms)
[ RUN      ] CalcTestkOpenCL.MapTypedBuffer
[       OK ] CalcTestkOpenCL.MapTypedBuffer (11 ms)
[ RUN      ] CalcTestkOpenCL.CompileExecutable
[       OK ] CalcTestkOpenCL.CompileExecutable (63 ms)
[ RUN      ] CalcTestkOpenCL.Execute
[       OK ] CalcTestkOpenCL.Execute (70 ms)
[ RUN      ] CalcTestkOpenCL.ExecuteRawParams
[       OK ] CalcTestkOpenCL.ExecuteRawParams (67 ms)
[----------] 13 tests from CalcTestkOpenCL (604 ms total)

[----------] 9 tests from CLW
[ RUN      ] CLW.BufferCreate
[       OK ] CLW.BufferCreate (10 ms)
[ RUN      ] CLW.BufferRead
[       OK ] CLW.BufferRead (11 ms)
[ RUN      ] CLW.BufferWrite
[       OK ] CLW.BufferWrite (11 ms)
[ RUN      ] CLW.ExclusiveScanSmall
[       OK ] CLW.ExclusiveScanSmall (932 ms)
[ RUN      ] CLW.ExclusiveScanSmallSizeDifference
[       OK ] CLW.ExclusiveScanSmallSizeDifference (917 ms)
[ RUN      ] CLW.ExclusiveScanLarge
[       OK ] CLW.ExclusiveScanLarge (1622 ms)
[ RUN      ] CLW.ExclusiveScanRandom
[       OK ] CLW.ExclusiveScanRandom (9127 ms)
[ RUN      ] CLW.CompactIdentity
[       OK ] CLW.CompactIdentity (923 ms)
[ RUN      ] CLW.RadixSortLarge
[       OK ] CLW.RadixSortLarge (3630 ms)
[----------] 9 tests from CLW (17183 ms total)

[----------] 2 tests from CLWCL
[ RUN      ] CLWCL.BufferRead
[       OK ] CLWCL.BufferRead (13 ms)
[ RUN      ] CLWCL.BufferWrite
[       OK ] CLWCL.BufferWrite (13 ms)
[----------] 2 tests from CLWCL (26 ms total)

[----------] 17 tests from ApiBackendOpenCL
[ RUN      ] ApiBackendOpenCL.DeviceEnum
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.DeviceEnum (16 ms)
[ RUN      ] ApiBackendOpenCL.SingleDevice
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.SingleDevice (15 ms)
[ RUN      ] ApiBackendOpenCL.Mesh
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Mesh (11 ms)
[ RUN      ] ApiBackendOpenCL.EmptyScene
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.EmptyScene (11 ms)
[ RUN      ] ApiBackendOpenCL.MeshStrided
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.MeshStrided (11 ms)
[ RUN      ] ApiBackendOpenCL.Instance
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Instance (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray (10 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_Active
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_Active (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_3Rays
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_3Rays (10 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_Transformed
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_Transformed (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_DynamicGeo
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_DynamicGeo (11 ms)
[ RUN      ] ApiBackendOpenCL.CornellBoxLoad
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.CornellBoxLoad (11 ms)
[ RUN      ] ApiBackendOpenCL.CornellBox_1Ray
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.CornellBox_1Ray (10 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance1
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance1 (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance2
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance2 (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstanceFlat
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstanceFlat (11 ms)
[ RUN      ] ApiBackendOpenCL.Intersection_1Ray_InstanceNoShape
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_InstanceNoShape (11 ms)
[----------] 17 tests from ApiBackendOpenCL (193 ms total)

[----------] 19 tests from ApiConformanceCL
[ RUN      ] ApiConformanceCL.CPU_CornellBox_1Ray_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1Ray_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_100RayRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_100RayRandom_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce (10 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce (10 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh (11 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_1RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1RandomRays_AnyHit_Bruteforce (12 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_AnyHit_Bruteforce (15 ms)
[ RUN      ] ApiConformanceCL.CPU_CornellBox_10000RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RandomRays_AnyHit_Bruteforce (12 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_1RandomRay_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1RandomRay_ClosestHit_Bruteforce (10 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_100RayRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_100RayRandom_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_10RaysRandom_ClosestHit_Force2level_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10RaysRandom_ClosestHit_Force2level_Bruteforce (10 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce (11 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh (11 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_1RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1RandomRays_AnyHit_Bruteforce (12 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_AnyHit_Bruteforce (10 ms)
[ RUN      ] ApiConformanceCL.GPU_CornellBox_10000RandomRays_AnyHit_Bruteforce
unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp().
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RandomRays_AnyHit_Bruteforce (11 ms)
[----------] 19 tests from ApiConformanceCL (211 ms total)

[----------] 7 tests from ApiCl
[ RUN      ] ApiCl.Intersection_1Ray
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_1Ray (11 ms)
[ RUN      ] ApiCl.ClBuffer
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.ClBuffer (11 ms)
[ RUN      ] ApiCl.Intersection_1Ray_Buffer
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_1Ray_Buffer (11 ms)
[ RUN      ] ApiCl.Intersection_3Rays_Buffer
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_3Rays_Buffer (11 ms)
[ RUN      ] ApiCl.Intersection_3Rays_Buffer_Indirect
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_3Rays_Buffer_Indirect (11 ms)
[ RUN      ] ApiCl.Intersection_Events
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_Events (11 ms)
[ RUN      ] ApiCl.Intersection_DependencyEvents
g:\projects\sdk\radeonrays_sdk-master\radeonrays_sdk-master\unittest\radeon_rays_test_cl.h(87): error: Expected: api_ = RadeonRays::CreateFromOpenClContext(rawcontext_, device, queue_) doesn't throw an exception.
  Actual: it throws.
[  FAILED  ] ApiCl.Intersection_DependencyEvents (11 ms)
[----------] 7 tests from ApiCl (77 ms total)

[----------] Global test environment tear-down
[==========] 67 tests from 6 test cases ran. (18295 ms total)
[  PASSED  ] 24 tests.
[  FAILED  ] 43 tests, listed below:
[  FAILED  ] ApiBackendOpenCL.DeviceEnum
[  FAILED  ] ApiBackendOpenCL.SingleDevice
[  FAILED  ] ApiBackendOpenCL.Mesh
[  FAILED  ] ApiBackendOpenCL.EmptyScene
[  FAILED  ] ApiBackendOpenCL.MeshStrided
[  FAILED  ] ApiBackendOpenCL.Instance
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_Active
[  FAILED  ] ApiBackendOpenCL.Intersection_3Rays
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_Transformed
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_DynamicGeo
[  FAILED  ] ApiBackendOpenCL.CornellBoxLoad
[  FAILED  ] ApiBackendOpenCL.CornellBox_1Ray
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance1
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstance2
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_TransformedInstanceFlat
[  FAILED  ] ApiBackendOpenCL.Intersection_1Ray_InstanceNoShape
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1Ray_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_100RayRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_1000RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiConformanceCL.CPU_CornellBox_10000RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1RandomRay_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_100RayRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RaysRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10RaysRandom_ClosestHit_Force2level_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RaysRandom_ClosestHit_Force2level_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_ClosestHit_Bruteforce_FatBvh
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_1000RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiConformanceCL.GPU_CornellBox_10000RandomRays_AnyHit_Bruteforce
[  FAILED  ] ApiCl.Intersection_1Ray
[  FAILED  ] ApiCl.ClBuffer
[  FAILED  ] ApiCl.Intersection_1Ray_Buffer
[  FAILED  ] ApiCl.Intersection_3Rays_Buffer
[  FAILED  ] ApiCl.Intersection_3Rays_Buffer_Indirect
[  FAILED  ] ApiCl.Intersection_Events
[  FAILED  ] ApiCl.Intersection_DependencyEvents

43 FAILED TESTS
  YOU HAVE 9 DISABLED TESTS

**Comment by itmanager85** [comment]
> cd to Radeon Rays' folder
cd to folder in another disk was not available .. :D 

and it's needs to change makefiles for add sample. after that I build project with sample but with freeglut this sample does not want to work .. runs "sample.exe" and gets error ..

**Comment by itmanager85** [comment]
debugged - all test ok :D 

and run demo :D 
https://i.paste.pics/7a72887c9ae6893037e5efc4d3e33174.png

AMD ! distribute the compiled SDK Installer in next time !!

**Comment by manhnt9** [comment]
remember to close this issue if all errors are gone.
