### ISSUE TITLE
Documentation 404

### ISSUE THREAD

**Issue by chfanghr** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#215]
The documentation link in README is broken.
![image](https://user-images.githubusercontent.com/40087668/94376380-d6557880-014c-11eb-927f-fd6150f5801e.png)

**Comment by bsavery** [comment]
Hmmm.  Does this work?  https://radeon-pro.github.io/RadeonProRenderDocs/en/sdk/about.html

**Comment by chfanghr** [comment]
@bsavery Yes👍Could you pls make a PR to update the README?

**Comment by bsavery** [comment]
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/pull/216 done.
