### ISSUE TITLE
where are the source codes of the trace kernels in radeon rays 4.1 ?

### ISSUE THREAD

**Issue by itmanager85** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#223]
where are the source codes of the trace kernels in radeon rays 4.1 ?

for example, where is "trace_scene_full_closest.comp" ? (in RadeonRays_SDK_4_1\src\core\src\vlk\kernels\) 

there is only "trace_scene_full_closest.comp.spv" ..

**Comment by PMunkes** [comment]
Here:
https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/blob/0ae7b214b8dcfb1efe22e0ab3ef6b3788ebd186c/src/core/src/vlk/kernels/CMakeLists.txt#L95
