### ISSUE TITLE
San Miguel issues

### ISSUE THREAD

**Issue by Woking-34** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#3]
Hi,

I'm doing some short tests with different scene setups. Managed to load Crytek's **Atrium Sponza** and 3drender.com's **Natural History Museum**, but the SDK fails to handle **San Miguel**. (First you have to manually create normals for the mesh.) I'm using the AO pass.

Can the SDK support such huge files? Have you managed to load and render other big scene files? Thanks.

**Comment by yozhijk** [comment]
The library itself supports arbitrary meshes as soon as it fits into GPU memory. San Miguel should work on cards having  >= 4Gb of memory. However simple obj loader which comes with an SDK is not optimized for huge files, so you might want to consider using your own loader.

**Comment by Woking-34** [comment]
Eventually I did manage to load the scene, so the SDK is clearly supporting huge files.
I changed the camera position/orientation and disabled g_benchmark to make it work - I guess the camera generated invalid rays or ray traversal failed with the initial setup.

**Comment by yozhijk** [comment]
Hi Woking-34,

Could you provide me with the asset and camera settings , so I will try to replicate invalid rays generation?

Thanks,
-Dmitry

**Comment by Woking-34** [comment]
Sure, thanks for checking on the issue!

My console log - the first part is my custom ocl dump:

CL_DEVICE_VENDOR:                   NVIDIA Corporation
CL_DEVICE_NAME:                     GeForce GTX 680
CL_DEVICE_VERSION:                  OpenCL 1.2 CUDA
CL_DRIVER_VERSION:                  364.51
CL_DEVICE_PROFILE:                  FULL_PROFILE

Loading complete
Number of objects: 381
Number of textures: 25
Vidmem usage (working set): 237Mb
Commited in 0.31s
Vidmem usage (data): 139Mb
Polygon count 262267
Starting the benchmark
----------------------
Number of primary rays: 786432
Bounce number 0
Number of rays: 786432
Average trace time: 38.96 ms
Average throuput: 20.1856 MRays/s
Number of shadow rays: 1572864
Average trace time: 55.72 ms
Average throuput: 28.228 MRays/s
----------------------
clEnqueueReadBuffer failedPress any key to continue . . .

**main.cpp** setup for crytek-sponza/**sponza.obj**:

int g_window_width = 1024;
int g_window_height = 768;
int g_ao_enabled = false;
int g_num_bounces = 1;
int g_num_samples = -1;
int g_samplecount = 0;
float g_ao_radius = 150.f;
float g_envmapmul = 100.f;

float3 g_camera_pos = float3(-400, 200, 0);
float3 g_camera_at = float3(1000, 300, 0);

int g_frame_count = 0;
bool g_benchmark = true;

The app just terminates after a while, sometimes after just a few iterations are successful.

![image](https://cloud.githubusercontent.com/assets/17589258/14261799/a0e21be0-fab2-11e5-851a-b6c797455fba.png)

**Comment by yozhijk** [comment]
@Woking-34 , should be fixed now
