### ISSUE TITLE
libFireRays.so has no SONAME

### ISSUE THREAD

**Issue by luigino** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#36]
Is it because the API is still unstable?

**Comment by yozhijk** [comment]
@beasterio , could you work on that?

**Comment by yozhijk** [comment]
Fixed: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/993a4d7e6ecf7880920b1176ac60f104264ca760
