### ISSUE TITLE
FireRays test app crashes when run in -config cpu mode

### ISSUE THREAD

**Issue by mrobin604** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#61]
When I run in config cpu, I get a crash after rendering 1-3 passes of Update(). The call stack is completely invalid so I don't know what's causing the crash exactly. Running in gpu mode, I get a driver crash on my home machine (GTX 980, driver 368.69) but my work machine seems to run ok (GTX 680, driver 353.30)

**Comment by yozhijk** [comment]
Hi @mrobin604 ,

Thanks for reporting. I will check CPU version shortly. The latest NV driver we tested was 364.72, so chances are their recent changes are breaking the renderer. I will be able to take a look at NV issue after Siggraph.

**Comment by beasterio** [comment]
Error occured because some shapes of i8.obj scene have no UV. Should be fixed now.

**Comment by yozhijk** [comment]
@mrobin604 , this happend due to insufficient geometry validation in sample renderer, nothing to do with the library. Fixed by @beasterio  here: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/007f52db61538b2040fdb1981b36374165b4890d
