### ISSUE TITLE
Threads not closing on Nvidia GPU's causing CLWException and Calc::ExceptionClw

### ISSUE THREAD

**Issue by jslater8** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#63]
There seems to be a problem when calling IntersectionApi::Delete with Nvidia cards. Threads don't seem to be deleted. When a large number of contexts are created and deleted, this causes an CLWException and Calc::Exception to be thrown. When tested on a Intel CPU OpenCL Device this doesn't occur.

Tested on:
Nvidia Geforce GT 710 368.69 and 368.39
Nvidia Geforce GTX 970m 365.10 and 368.69

Both systems have this problem.

**Comment by yozhijk** [comment]
Hi @jslater8 ,

Could you describe your repro steps? Is it happening with embree enabled?

**Comment by yozhijk** [comment]
Closing as obsolete
