### ISSUE TITLE
Win, Nvidia 1070 and 970: clFinish : CL_INVALID_COMMAND_QUEUE  (-36)

### ISSUE THREAD

**Issue by dubik** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#65]
On windows 10, with nvidia 1070 and 970, demo app consistently fails with invalid command queue, usually in clFinish but some times in clEnqueueReadBuffer. It renders several iterations and then gets an error. I can see that queue is valid, if I query ref counter, it shows there is 6 or 7. GPU-Z shows 550-600Mb used in 1070, so it shouldn't run out of memory. Few times windows rebooted because of issues with drivers, may be kernels take too much time to compute and gpu doesn't respond in time?

**Comment by yozhijk** [comment]
Hi @dubik ,

What is the driver version? @beasterio is currentlu working on CPU issue which might have the same roots, stay tuned.

**Comment by dubik** [comment]
Hi @yozhijk,
I had latest, from website by that time - 368.81.

**Comment by yozhijk** [comment]
Fixed in https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/pull/122/commits/31d2b387781e993e7ea85dc08b177271ba308e90
