### ISSUE TITLE
ETA for Vulkan port?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#68]
I see from The Quest for the Ray Tracing API slides Radeon Rays has a Vulkan port..
is that coming soon?

**Comment by yozhijk** [comment]
Hi @oscarbg ,

We are releasing it beginning of next week.

**Comment by DeanoC** [comment]
Hi,
Its available in the Vulkan branch at the moment, still alpha as its cleaned up and unit tests passed. Right now it passes about 80% of the unit tests.

**Comment by yozhijk** [comment]
Thanks @DeanoC , I think I can close this issue since the code is already available.
