### ISSUE TITLE
Embree backend (on Vulkan branch) fails a few unit tests

### ISSUE THREAD

**Issue by DeanoC** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#74]
Vulkan branch adds the unit tests to Embree and its failing a few

ApiConformanceEmbree fails the 3 CornellBox_1XXXXRandomRays_AnyHit_Bruteforce tests (XXXX = 100,1000,10000 rays)

**Comment by yozhijk** [comment]
Fixed https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/adc731cc77233f7b38c77486c0ac09533c56e7f4
