### ISSUE TITLE
Nondescript "clEnqueueFillBuffer failed" Error

### ISSUE THREAD

**Issue by nearFar** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#9]
Getting this error immediately when trying the App with no special settings.

GPU : NVidia GTX 550 Ti ( OpenCL 1.2 )

At first i thought this was the error-message from the CLWBuffer Code, but it's not - after some headscratching trying to edit this message with more information, and it seemingly never using the new code changes, it turned out the FireRays.dll also has this exact same error-message embedded.
So i guess this error is coming from inside FireRays.dll instead.

It would be nice to see a more descriptive error in this case, to know what exactly went wrong.
I guess once the full SDK code is available this becomes a non issue :)

**Comment by yozhijk** [comment]
GTX550 Ti does not support OCL1.2 according to nvidia specs, could you please attach your CL info?

**Comment by yozhijk** [comment]
Closing as source code is not published
