### ISSUE TITLE
Ubuntu 15.10 Compilation Fails

### ISSUE THREAD

**Issue by xoryouyou** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#90]
Hello there,

I wanted to compile the SDK and followed the README.

During this I encountered this Error

    Linking RadeonRays
    /usr/bin/ld: ../Bin/Release/x64/libCalc64.a(calc.o): relocation R_X86_64_32 against `.bss' can not     be used when making a shared object; recompile with -fPIC
    ../Bin/Release/x64/libCalc64.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:165: recipe for target '../Bin/Release/x64/libRadeonRays64.so' failed
    make[1]: *** [../Bin/Release/x64/libRadeonRays64.so] Error 1
    Makefile:54: recipe for target 'RadeonRays' failed
    make: *** [RadeonRays] Error 2

I used `./Tools/premake/linux64/premake5 gmake` to create the makefile

    >> OpenCL backend enabled
    Building configurations...
    Running action 'gmake'...
    Generated Makefile...
    Generated RadeonRays/Makefile...
    Generated Calc/Makefile...
    Generated CLW/Makefile...
    Generated App/Makefile...
    Generated Gtest/Makefile...
    Generated UnitTest/Makefile...
    Done (162ms).

 and maked with `make config=release_x64` which then resulted in the error above.

My libraries/compiler  are as following:

    g++:
      Installed: 4:5.2.1-3ubuntu1
    libopenimageio-dev:
      Installed: 1.6.10-0thomas~wily1
    libglew-dev:
      Installed: 1.10.0-3
    libglew-dev:
      Installed: 1.10.0-3
    nvidia-opencl-dev:
      Installed: 6.5.14-2

Is this a known error and is there a workaround ?

**Comment by yozhijk** [comment]
Hi @xoryouyou ,

Can you try running premake with --shared_calc option enabled?

**Comment by yozhijk** [comment]
@beasterio , could you please check Linux build? Most likely we need to add "-fPIC" for Calc library.

**Comment by xoryouyou** [comment]
Hi @yozhijk ,

` ./Tools/premake/linux64/premake5 --shared_calc` resulted in

    >> Building Calc as a shared library
    >> OpenCL backend enabled
    Type 'premake5 --help' for help


So not sure about the leaking help info line there but it just ran into the same issue


    ==== Building RadeonRays (release_x64) ====
    Linking RadeonRays
    /usr/bin/ld: ../Bin/Release/x64/libCalc64.a(calc.o): relocation R_X86_64_32 against `.bss' can not     be used when making a shared object; recompile with -fPIC
    ../Bin/Release/x64/libCalc64.a: error adding symbols: Bad value
    collect2: error: ld returned 1 exit status
    Makefile:165: recipe for target '../Bin/Release/x64/libRadeonRays64.so' failed
    make[1]: *** [../Bin/Release/x64/libRadeonRays64.so] Error 1
    Makefile:54: recipe for target 'RadeonRays' failed
    make: *** [RadeonRays] Error 2

**Comment by yozhijk** [comment]
Seems like it is still trying to build static one. Can you try the following:

rm -rf Calc/obj RadeonRays/obj
./Tools/premake/linux64/premake5 --shared_calc gmake 
make config=release_x64

**Comment by xoryouyou** [comment]
Woops forgot the `gmake` last time i'm sorry.

Now its getting a bit further down but also it seems `-libdl` is missing

    ==== Building RadeonRays (release_x64) ====
    Creating obj/x64/Release
    bvh.cpp
    hlbvh.cpp
    split_bvh.cpp
    calc_intersection_device.cpp
    calc_intersection_device_cl.cpp
    calc_intersection_device_vk.cpp
    radeon_rays.cpp
    radeon_rays_impl.cpp
    mesh.cpp
    bvh2lstrategy.cpp
    bvhstrategy.cpp
    fatbvhstrategy.cpp
    hlbvh_strategy.cpp
    fatnode_bvh_translator.cpp
    plain_bvh_translator.cpp
    options.cpp
    world.cpp
    Linking RadeonRays
obj/x64/Release/radeon_rays.o: In function `RadeonRays::GetCalcEntryPoint(Calc::Platform, char     const*) [clone .isra.1]':
    radeon_rays.cpp:(.text+0x11): undefined reference to `dlopen'
    radeon_rays.cpp:(.text+0x3d): undefined reference to `dlopen'
    radeon_rays.cpp:(.text+0x22): undefined reference to `dlsym'
    collect2: error: ld returned 1 exit status
    Makefile:165: recipe for target '../Bin/Release/x64/libRadeonRays64.so' failed
    make[1]: *** [../Bin/Release/x64/libRadeonRays64.so] Error 1
    Makefile:54: recipe for target 'RadeonRays' failed
    make: *** [RadeonRays] Error 2

**Comment by yozhijk** [comment]
Ok, this should be easy to fix by including the links {"dl"} line into RadeonRays.lua

  if _OPTIONS["shared_calc"] then
        defines {"CALC_IMPORT_API"};
        links{"dl"}
    else
	defines {"CALC_STATIC_LIBRARY"}
        links {"Calc"}
	if _OPTIONS["use_opencl"] then
           links {"CLW"}
	end
    end

**Comment by yozhijk** [comment]
You'll need to rerun premake again

**Comment by xoryouyou** [comment]
I've include the `links{"dl"}` you posted earlier in the `if branch` and now it's missing the OpenImageIO objects

    ==== Building App (release_x64) ====
    Creating obj/x64/Release
    aorenderer.cpp
    Ibl.cpp
    ptrenderer.cpp
    scene.cpp
    scene_tracker.cpp
    config_manager.cpp
    main.cpp
    perspective_camera.cpp
    sh.cpp
    shader_manager.cpp
    shproject.cpp
    tiny_obj_loader.cpp
    Linking App
    obj/x64/Release/Ibl.o: In function `Baikal::Ibl::DumpPdf(std::string const&)':
    Ibl.cpp:(.text+0x663): undefined reference to `OpenImageIO::v1_6::ImageOutput::create(std::string const&, std::string const&)'
    obj/x64/Release/Ibl.o: In function `Baikal::Ibl::Simulate(std::string const&)':
Ibl.cpp:(.text+0xa5a): undefined reference to `OpenImageIO::v1_6::ImageOutput::create(std::string const&, std::string const&)'
obj/x64/Release/scene.o: In function `Baikal::LoadTexture(std::string const&, Baikal::Scene::Texture&, std::vector<std::unique_ptr<char [], std::default_delete<char []> >, std::allocator<std::unique_ptr<char [], std::default_delete<char []> > > >&)':
    scene.cpp:(.text+0xaa): undefined reference to `OpenImageIO::v1_6::ImageInput::open(std::string const&, OpenImageIO::v1_6::ImageSpec const*)'
    obj/x64/Release/main.o: In function `SaveFrameBuffer(std::string const&, RadeonRays::float3 const*)':
    main.cpp:(.text+0x182c): undefined reference to `OpenImageIO::v1_6::ImageOutput::create(std::string const&, std::string const&)'
    collect2: error: ld returned 1 exit status
    Makefile:148: recipe for target '../Bin/Release/x64/App64' failed
    make[1]: *** [../Bin/Release/x64/App64] Error 1
    Makefile:72: recipe for target 'App' failed
    make: *** [App] Error 2


Btw was it known to work under ubuntu/linux at some point in time ?

**Comment by yozhijk** [comment]
@xoryouyou , sure it has always been working on Linux. Seems our recent changes with dynamically linked Calc have broken the compatibility. Let @beasterio fix it.

**Comment by xoryouyou** [comment]
@yozhijk ok , just thought I was too dump to set it up correctly or something.

Thanks for the help anyways i'll check back when @beasterio has something to enlighten us :)

**Comment by yozhijk** [comment]
@xoryouyou this commit is supposed to fix Linux build issues with -fPIC an ldl: https://github.com/GPUOpen-LibrariesAndSDKs/RadeonRays_SDK/commit/e5c8e65547f3e8df9835189a69620d3618575b6f
I tested it on Ubuntu 16.04.
The issue with OpenImageIO is a bit weird though. The App on Linux uses OpenImageIO distribution which comes with a system (this is usually either 1.5 or 1.6 on recent distributions). On your system it looks like it tries to link against different version of OIIO while using the headers from 1.6. Can you check it the symbolic link libOpenImageIO.so is correctly resolved to 1.6?

**Comment by xoryouyou** [comment]
@yozhijk  Hmm you didn't encounter the OIIO bug on 16.04 ?

    ls -l /usr/lib/libOpenImageIO.so
    lrwxrwxrwx 1 root root 21 Feb 13  2016 /usr/lib/libOpenImageIO.so -> libOpenImageIO.so.1.6

The version seems to be alright  but im using a repo for it `http://ppa.launchpad.net/thomas-schiex/blender/ubuntu/ wily/main amd64 Packages `  from which im usually getting blender.

So i'll check if there is some version mismatch happening.

**Comment by yozhijk** [comment]
@xoryouyou Nope, on 16.04 it is just fine. And actually I have just checked on 15.10 and it works fine as well. But the difference is the machine I found (with 15.10) has oiio 1.5 installed by default.

**Comment by xoryouyou** [comment]
Yes that was the fault, removed 1.5 and installed 1.6 and now everything works fine.

Thanks a lot for the help!
