### ISSUE TITLE
Linker error LNK1104 for  when compiling app target in VS2015

### ISSUE THREAD

**Issue by Erikmolin** [GPUOpen-LibrariesAndSDKs/RadeonRays_SDK#92]
I'm having trouble setting up the SDK on my windows machine; trying to compile the App target in VS2015 renders the following error:

Error   : LNK1104   cannot open file 'OpenImageIOD.lib' App C:\Users\cons-elo\Source\Repos\RadeonRays_SDK\App\LINK

I'm also having trouble with tests - most of them fail with the error "unknown file: error: C++ exception with description "Cannot read the contents of a file" thrown in SetUp()."

Cheers,
Erik

**Comment by yozhijk** [comment]
Hi @Erikmolin ,

Most likely you are trying to compile x32 version. We do not support it, so switch to x64 and it should be ok. Are you running the test from within Visual Studio?

**Comment by yozhijk** [comment]
@Erikmolin , did it solve your issue?

**Comment by Erikmolin** [comment]
Hi, and thank  you for you reply.

Now it compiles fine, however, when running, I get error messages complaining about missing OpenImageIOD.dll, and freeglut.dll.

**Comment by Erikmolin** [comment]
@yozhijk Thank you again for your quick response - now i get the more anonymous error "The application was unable to start correctly (0xc000007b)".. Which seems to be a quite general error, judging by search results. Any specific ideas?

**Comment by markusfehr** [comment]
I think you also have to copy the "glew32.dll" File in your directory.

**Comment by yozhijk** [comment]
@Erikmolin , that usually happens if you have a version of glew32.dll or freeglut.dll in your windows/system32, which is different from our version in 3rdparty. To be safe, just remove your lib from windows/system32 and copy the one from 3rdparty/glew/bin/x64 to bin/release/x64, this should solve you problem.
